### PR TITLE
respect existing render MELs

### PR DESCRIPTION
**Pull request by campbells**
- if user or other 3rd parties have pre/post-renderMELs installed, dont
overwrite them.

### CODE REVIEW

**Comment by campbells** [comment]
Hey, I'm a dev for the 'Molecualr Maya' project. We were having issues with one of our clients, which we finally narrowed down to our renderMELs being unexpectedly removed, and Domemaster was responsible (tutut! ;p).

Please find a commit here that'll respect any existing renderMELs.

Cheers!
Campbell.

**Comment by AndrewHazelden** [comment]
Thanks Campbell! I will go over this pull request and integrate your revisions into the different Domemaster3D for Maya renderer versions.

**Comment by campbells** [comment]
Hey Andrew. Great.

Just realised it'd also need to respect any existing renderMELs in removePrePostRenderScript() too, rather than just clearing whatever is there.

I wont be in office to make those mods for a while, but i'd imagine simply moving the post/preMEL_domemaster to the module scope, and then doing something like:

`cmds.setAttr('defaultRenderGlobals.preMel', cmds.setAttr(preMEL_cur.replace(preMEL_domemaster, ''), type='string')`

, and for postMEL, to strip them out. No matter if semicolons stack up.

My client would definitely appreciate a release with these mods in as soon as convenient for you. Also, i imagine this'd have wide impacts on other users too.

Thanks!
C.

**Comment by campbells** [comment]
or, use GitHub's editor! Nice.

Untested code revisions.

Thanks,
C.

**Comment by AndrewHazelden** [comment]
Hi Campbell. 

I went over your submission this morning and fixed a few small syntax errors. This revision is included in the master branch of Domemaster3D on GitHub.

The following note was added to the Domemaster3D Readme.txt file:

>   Added support for preserving existing pre/post render MEL script entries when Domemaster3D adds a new camera rig to the scene, or you click the "Add" / "Rem" shelf buttons. This revision is based upon a submission from Campbell Strong.

**Comment by campbells** [comment]
Beauty, thanks Andrew!

**Pull request merged**
